language: python

python:
  - "2.7"

addons:
  apt:
    packages: 
      - wget
      - libcups2-dev
    
virtualenv:
  system_site_packages: true

before_install:
  - pip install invoke
  - git config --global user.name "TravisCI"
  - git config --global user.email "travis@camptocamp.com"

install: 
  - git submodule update --init
  - invoke env.init -s -r -p profiles/dev.cfg
  - bin/buildout -N -v

before_script:
  - pip install -q flake8
  - export db_name=$(grep db_name ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export db_user=$(grep db_user ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export db_pass=$(grep db_password ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - psql -c "CREATE USER ${db_user} WITH PASSWORD '${db_pass}' CREATEDB;" -U postgres

script:
  - flake8 ${TRAVIS_BUILD_DIR}/specific-parts/specific-addons --exclude=__init__.py

